### ISSUE TITLE
Alter on table error "Invalid operation: must be owner of relation"

### ISSUE THREAD

**Issue by pkchuyen** [philsch/ansible-redshift#11]
Hi,

I have an error when try to grant a User with full privileges which is supposed that he is able to create new tables, select, insert, update, delete on all tables in a schema.
That is working great with the current redshift_user module. But he has a problem when try adding a new column which was created by other users.

```[Amazon](500310) Invalid operation: must be owner of relation fact_order_line_items;```

I understand that it relates to owner permission of psql. There is anyway that we can provide a user with ALTER privileges to add, delete an column on the tables which is created by other users in Redshift?

Sorry for the silly question,

Thanks

**Comment by philsch** [comment]
Hi @pkchuyen 

It is a restriction from PostgreSQL (and therefore Redshift), that only the owner of a relation is allowed to `ALTER` it. As written in https://www.postgresql.org/docs/current/static/sql-altertable.html:

> You must own the table to use ALTER TABLE. To change the schema or tablespace of a table, you must also have CREATE privilege on the new schema or tablespace. To add the table as a new child of a parent table, you must own the parent table as well. Also, to attach a table as a new partition of the table, you must own the table being attached. To alter the owner, you must also be a direct or indirect member of the new owning role, and that role must have CREATE privilege on the table's schema. (These restrictions enforce that altering the owner doesn't do anything you couldn't do by dropping and recreating the table. However, a superuser can alter ownership of any table anyway.) To add a column or alter a column type or use the OF clause, you must also have USAGE privilege on the data type.

So you only have 2 possibilities:

- Use the same user for creating and altering the table
- Change the owner of the table, apply your ALTER statements, change the owner back. Changing the owner has its pitfalls, [this StackOverflow question](https://stackoverflow.com/questions/28584640/postgresql-error-must-be-owner-of-relation-when-changing-a-owner-object) might help you

Best,
Philipp
