### ISSUE TITLE
'pg_roles doesnt exist'

### ISSUE THREAD

**Issue by smcaine** [philsch/ansible-redshift#17]
Hi,

im getting this error whenever I try to run create user.. i got this error when trying to use the postgres module too. It happens when trying to create user or when i try to re-run the postgres create db (it tries to check this table but fails).

This catalog doesnt appear to exist when creating redshift db's.. even the maintenance db i created via aws console. 

Im suprised no one seems to have come across this before. Any ideas on this would be much appreciated.

Thanks
Stuart

**Comment by philsch** [comment]
Hi @smcaine,

This module is not referencing any table `pg_roles`. Can you maybe check your project if you are referencing this table somewhere?

Can you also provide your ansible log in verbose mode (by appending `-vvv`) so I can try to investigate the problem you are facing?

Best,
Philipp

**Comment by smcaine** [comment]
yeah sorry this is my bad, it is working... i was just using the postgres_db module with it which was failing before this was running..
